server:
  port: 8082

jwt:
  secret: r1Wq3Y7Ql8ivrpC4A6vEgBg1kllCKCrFkwhbZUNZ6Y8=
  lifetime: 30m
  refresh:
    expiration: 1d

spring:
  application:
    name: USER-APP
  cloud:
    discovery:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5435/notification
    username: notification
    password: notification
  flyway:
    enabled: true
    locations:
      - migrations

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    enabled: true