server:
  port: 8082

jwt:
  secret: r1Wq3Y7Ql8ivrpC4A6vEgBg1kllCKCrFkwhbZUNZ6Y8=
  lifetime: 30m
  refresh:
    expiration: 1d

spring:
  application:
    name: NOTIFICATION-SERVICE

  cloud:
    discovery:
      enabled: true

  kafka:
    topic:
      notification: notification-topic
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5435/notification
    username: notification
    password: notification

  flyway:
    enabled: true
    locations:
      - migrations

  mail:
    host: smtp.gmail.com
    port: 587
    username: alex.rashevskiy222@gmail.com
    password: mlgowogybtytfomo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    enabled: true