version: '3.9'
services:
  db:
    container_name: forum-db
    image: postgres:12
    hostname: forum-db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=forum
      - POSTGRES_USER=forum
      - POSTGRES_PASSWORD=forum
    ports:
      - "5430:5432"

volumes:
  db-data:
