version: '3.9'
services:
  db:
    container_name: user-db
    image: postgres:12
    hostname: user-db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=user
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    ports:
      - "5431:5432"

volumes:
  db-data:
