minio:
  accessKey: accesskey
  secretKey: secretkey
  endpoint: http://localhost:9000
  bucket:
    name: ilovehitsandbackend

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5430/file
    username: file
    password: file
  flyway:
    enabled: true
    locations:
      - db.migration

springdoc:
  swagger-ui:
    enabled: true