server:
  port: 8080

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: forum-core
          uri: lb://FORUM-CORE
          predicates:
            - Path=api/forum/**

        - id: user-app
          uri: lb://USER-APP
          predicates:
            - Path=api/users/**
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG