server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: forum-core
          uri: http://localhost:8081/
          predicates:
            - Path=api/forum/**

        - id: user-app
          uri: http://localhost:8082/
          predicates:
            - Path=api/users/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    enabled: true

