server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: forum-core
          uri: http://localhost:8081/
          predicates:
            - Path=api/forum/**

        - id: user-app
          uri: http://localhost:8082/
          predicates:
            - Path=api/users/**
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  main:
    web-application-type: reactive
springdoc:
  swagger-ui:
    enabled: true

