server:
  port: 8083

jwt:
  secret: r1Wq3Y7Ql8ivrpC4A6vEgBg1kllCKCrFkwhbZUNZ6Y8=
  lifetime: 30m
  refresh:
    expiration: 1d

spring:
  application:
    name: FILE-SERVICE
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5433/file
    username: file
    password: file
  flyway:
    enabled: true
    locations:
      - migrations

minio:
  accessKey: accesskey
  secretKey: secretkey
  endpoint: http://localhost:9000
  bucket:
    name: ilovehitsandbackendtoo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    enabled: true
