server:
  port: 8082

jwt:
  secret: r1Wq3Y7Ql8ivrpC4A6vEgBg1kllCKCrFkwhbZUNZ6Y8=
  lifetime: 30m

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5431/user
    username: user
    password: user
  flyway:
    enabled: true
    locations:
      - migrations

springdoc:
  swagger-ui:
    enabled: true