server:
  port: 8084

jwt:
  secret: r1Wq3Y7Ql8ivrpC4A6vEgBg1kllCKCrFkwhbZUNZ6Y8=
  lifetime: 30m
  refresh:
    expiration: 1d

spring:
  application:
    name: USER-APP
  cloud:
    discovery:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5431/user
    username: user
    password: user
  flyway:
    enabled: true
    locations:
      - migrations
  mail:
    host: smtp.gmail.com
    port: 587
    username: alex.rashevskiy222@gmail.com
    password: mlgowogybtytfomo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    enabled: true