server:
  port: 8081

jwt:
  secret: r1Wq3Y7Ql8ivrpC4A6vEgBg1kllCKCrFkwhbZUNZ6Y8=
  lifetime: 30m
  refresh:
    expiration: 1d

spring:
  application:
    name: FORUM-CORE

  cloud:
    discovery:
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
  kafka:
    topic:
      notification: notification-topic
      message: message-topic
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:postgresql://localhost:5430/forum
    username: forum
    password: forum

  flyway:
    enabled: true
    locations:
      - migrations

springdoc:
  swagger-ui:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

