server:
  port: 8080

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5430/forum
    username: forum
    password: forum
  flyway:
    enabled: true
    locations:
      - migrations

springdoc:
  swagger-ui:
    enabled: true