server:
  port: 8081

jwt:
  secret: r1Wq3Y7Ql8ivrpC4A6vEgBg1kllCKCrFkwhbZUNZ6Y8=
  lifetime: 30m

spring:
  application:
    name: FORUM-CORE
  cloud:
    discovery:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5430/forum
    username: forum
    password: forum
  flyway:
    enabled: true
    locations:
      - migrations

springdoc:
  swagger-ui:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: DEBUG
    org:
      springframework: DEBUG
      hibernate: DEBUG
    net:
      bytebuddy: WARN